name: build docker image and release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Bump tag type: major, minor, patch. default: minor"
        required: true
        default: "minor"

permissions: write-all
jobs:
  release:
    name: Docker image and release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Bump tag version
        id: bumpTag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: "${{ github.event.inputs.bump_type }}"
      - name: Bump tag locally
        run: git tag ${{ steps.bumpTag.outputs.new_tag }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Landing Page Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.bumpTag.outputs.new_tag }}
            ghcr.io/${{ github.repository }}:latest
